gamersclub-booster/gamersclub-booster

manifest.json, pages/profile/profile.js
=> Feature profile winratio

README.md, pages/minhas-partidas/minhas-partidas.js
=> Adiciona cor para vitória/derrota/empate na página minhas partidas

manifest.json, pages/lobby/lobby.js
Corrige a issue #28 reportado pelo @davidhirle
=> Adiciona o endereço csgo.gamersclub.gg as permissões

pages/lobby/lobby.js
arrumando o fixedmenu para os membros free
=> fix-fixedmenu

pages/geral/index.js
=> Refatorei e add a mudança de pontos

opcoes/opcoes.css, opcoes/opcoes.html
- Adicionados estilos iguais ao da Gamers Club
- Botões
- Success (verde)
- Warning (amarelo)
- Primary (azul)
- Selects
- Inputs
- Troca da fonte usada nos items do menu para Teko
=> styles: adiciona estilo padrão para botões e inputs

src/lib/discord.js
Modificado onde estava escrito "viória" para "vitória"
=> Atualização na ortografia do discord.js

src/content-scripts/lobby/lobbyLink.js, src/lib/discord.js
Hello guys, this is my first contribution! 😄
Besides I understand a lot of Portuguese (thanks to CS), I'm so bad at writing Portuguese so I prefer to write in English.
- Fix Discord logo image url.
- Fix pre-vetos text in Discord message.
=> fix: Discord lobby message

src/content-scripts/main/barraLevel.js
Barra de level agora é toda feita com jquery ao invés de HTML dentro do javascript. Assim, a leitura é mais fácil, pois temos syntax highlight, e também conseguimos usar as variáveis sem precisar do $().
Também tem uma tentativa de corrigir o bug do nv21 na barra, mas não sei se vai funcionar, pois não tenho como testar xD
=> Enhancement barra level

package-lock.json, src/content-scripts/lobby/index.js, src/content-scripts/lobby/mostrarKdr.js
Fiz uma alteração bem simples para exibir os KDR's na aba de desafios também, além de atualizar o webpack.
=> Alteração para mostrar o KDR na aba de desafios. Webpack atualizado.

src/content-scripts/main/autoDailyRewards.js, src/content-scripts/main/index.js, src/lib/constants.js, src/options/index.html, src/translations/en.json, src/translations/es.json, src/translations/pt.json
Adicionei uma função para coletar automaticamente as recompensas do Daily Rewards diariamente.
=> feat: adicionada função para coletar automaticamente o Daily Rewards

.eslintrc, package-lock.json, package.json, src/content-scripts/main/autoDailyRewards.js
=> feat: torna como lido o link do Daily Rewards no menu ao fazer a coleta

src/content-scripts/main/barraLevel.js
Corrige diferença na pontuação quando o jogador perde pontos por
inatividade.
Busca informações do usuário de forma mais precisa.
Esse PR corrige a issue #116.
=> fix: corrige bug na exibição dos pontos

src/content-scripts/main/barraLevel.js
Corrige a issue #153 usando a sugestão do @henriquelbsouza.
Não tenho um conta inativa pra testar melhor a solução, se alguém puder ajudar seria perfeito.
=> fix: corrige link da partida na barra de level

src/content-scripts/lobby/filtrarKdr.js, src/content-scripts/lobby/index.js, src/content-scripts/lobby/mostrarKdr.js
=> feat: adiciona filtro por KDR na lobby

manifest.json
vi na live do nak que não da autoready se puxar ranked estando nessa tela de /hub/*
=> fix: adiciona /hub pra carregar os scripts de lobby

README.md
Olá, apenas adicionei a descrição da funcionalidade de integração com o Discord.
=> Descrição da integração com o Discord

DISCORD.md
Olá, adicionei mais algumas imagens para ilustrar a explicação.
=> Adicionadas imagens

.vscode/settings.json, public/styles.css, src/content-scripts/content.css, src/content-scripts/lobby/listaBloqueio.js, src/options/index.js
Adicionando e removendo da lista de bloqueios, adicionado tambem o margin para melhorar a lista, adicionado tambem vermelho na sala quando tiver um bloqueado, falta apenas mostrar no lobby
=> fix: melhorias na lista de bloqueios

src/content-scripts/content.css, src/content-scripts/lobby/filtrarPais.js, src/content-scripts/lobby/index.js
=> feat: adicionado filtro de paises

.all-contributorsrc, src/content-scripts/lobby/botaoAutoComplete.js, src/content-scripts/lobby/botaoForcarCriarLobby.js, src/content-scripts/lobby/botaoListaBloqueio.js, src/translations/en.json, src/translations/es.json, src/translations/fr.json, src/translations/pt.json, src/utils/index.js
- Adicionado tradução aos seguintes botões/textos: `Adicionar a lista de bloqueio`, `COMPLETAR PARTIDA`, `CRIAR LOBBY PRE CONFIGURADA` de acordo com a língua escolhida na extensão.
- Removi alguns async/await que não faziam efeito.
- Troquei o `alertaMsg` pelo `alert` padrão do JS, pois ele não estava funcionando nem com reza brava. (se puderem me ajudar pra fazer funcionar o alertaMsg eu troco novamente sem problema)
- Gostaria que alguém validasse as traduções, principalmente as do francês e espanhol.
- Criei uma pasta utils para ter funções como `getAllStorageSyncData` e `getTranslationText`
- `getTranslationText`: pra pegar o texto traduzido dos `.json` de forma centralizada. (da pra melhorar ela futuramente)
- `getAllStorageSyncData`: pra pegar as informações do storage de forma …
=> feat: translate actions in the pages

src/content-scripts/lobby/mostrarKdr.js
Basicamente adicionei uma cache layer...
=> fix: evita fazer muitos requests pra montar o kdr na lobby

src/content-scripts/profile/index.js
added kill/death/(diff|kdr) visualization of current month in profile
=> feat: added kill/death/(diff|kdr) visualization of current month

src/content-scripts/profile/index.js
=> feat: added representative color for KDR stats and win rate;+

src/content-scripts/main/autoDailyRewards.js
Não testei ainda, vou testar durante a semana que vem, se funcionar faço o merge.
=> fix: corrige o daily rewards

src/content-scripts/lobby/partidaInfo.js, src/content-scripts/team/matches.js
Corrige erros simples de digitação.
=> fix: corrige erro de digitação

src/lib/discord.js
[Adicionar os nomes do time na lobby #264](https://github.com/gamersclub-booster/gamersclub-booster/issues/264)
=> feat: add admin nicks as teams name instead generic teams name

.vscode/settings.json, src/content-scripts/lobby/index.js, src/content-scripts/lobby/infoLobby.js, src/content-scripts/lobby/partidaInfo.js, src/lib/constants.js, src/lib/discord.js, src/options/index.html, src/translations/pt.json
Adicionado warmup timer na janela de lobby e o tempo final do warmup na mensagem enviada pelo discord webhook.
Adicionado lobby info nos challenges recebidos.
=> feat: adicionado warmup timer e lobby info nos challenges

src/content-scripts/lobby/index.js, src/content-scripts/lobby/mostrarKdr.js
Preview ![photo1676489567](https://user-images.githubusercontent.com/1965127/219133621-94089e25-c639-4dde-813e-07b68d2dbad6.jpeg)
=> Mostrar KDR na escolha de players da ranked - issue #161

src/content-scripts/main/barraLevel.js, src/lib/maps.js
=> fix: corrige a barra de level, pra só adicionar se o player estiver logado

public/styles.css, src/options/index.html, src/options/index.js, src/translations/en.json, src/translations/es.json, src/translations/fr.json, src/translations/pt.json
Mudanças gerais na parte do discord para ter multiplos
Mudanças nos menus de seleção para manter o padrão em todos
Mudança no select de todos para deixar mais padrão e bonito
Redesign na lista de bloqueados
=> feat: add tasks do discord para multiplos

src/options/index.html, src/translations/en.json, src/translations/es.json, src/translations/fr.json, src/translations/pt.json
=> fix: Pula linha da opção contato & Tradução opção discord (Nome do servidor)

src/content-scripts/content.css, src/content-scripts/main/barraLevel.js
To começando a usar um editor de código novo (nvim) e aí fiz uma pequena melhoria (foi o que deu tempo) aí para tirar a barra de level de cima de outros elementos que estão na barra da GC. Joguei ela lá para baixo.
Acho que não vale um release só para essa mudança, mas fica aí o PR.
=> fix: level bar position

public/styles.css, src/lib/constants.js, src/options/index.js
=> feat: desativa o botão "Testar" e o slider de volume se o som do "Aceitar ready" for o padrão

src/content-scripts/content.css, src/content-scripts/lobby/index.js, src/content-scripts/lobby/ocultarSugestaoDeLobbies.js, src/lib/constants.js, src/options/index.html, src/translations/en.json, src/translations/es.json, src/translations/fr.json, src/translations/pt.json
Oculta essas sugestões abaixo:
=> feat: adiciona função para esconder sugestões de lobbies para entrar

src/content-scripts/content.css, src/content-scripts/lobby/botaoAutoComplete.js, src/content-scripts/lobby/botaoListaBloqueio.js, src/content-scripts/lobby/filtrarKdr.js, src/content-scripts/lobby/infoLobby.js, src/content-scripts/lobby/mostrarKdr.js, src/options/index.html
Novas feats para layout e clean code
=> feat: add new layout and code refector

src/content-scripts/lobby/mostrarKdr.js
Adicionei o código anterior e funcionou, vou refatorar novamente depois, por enquanto vamos manter esse.
=> fix: corrige o KDR para salas ja prontas

src/content-scripts/lobby/botaoAutoComplete.js, src/content-scripts/lobby/botaoForcarCriarLobby.js, src/content-scripts/lobby/botaoListaBloqueio.js, src/content-scripts/lobby/infoLobby.js, src/content-scripts/lobby/partidaInfo.js, src/content-scripts/main/barraLevel.js
Adiciona o title com o [GC Booster]: para todas as funções e itens.
=> feat: add new title for all functions booster

src/content-scripts/lobby/index.js, src/content-scripts/main/autoDarkMode.js, src/lib/discord.js
Remove lobby rapida, changed background to black and remove null of password.
=> feat: change dark mode, fixed discord link and remove lobby rapida

src/lib/discord.js
Corrige a senha da sala que estava vindo como null, fui arrumar e foi true, corrigi a variavel
=> fix: improviments password

src/content-scripts/profile/index.js
Volta a mostrar as estatísticas no box de histórico do player :)
=> fix: corrige as stats do histórico no perfil

src/content-scripts/content.css
Melhorias para manutenção do CSS
Correção do botão Kick
=> feat: melhorias gerais no CSS

src/content-scripts/content.css
=> feat: subida do css pra melhorar compact

src/content-scripts/lobby/mostrarKdr.js
Corração do Undefined quando 0 e cor
=> fix: corrige cor do KDR

src/content-scripts/content.css, src/content-scripts/lobby/infoLobby.js
=> Feature/spinner infoLobby

src/content-scripts/lobby/infoLobby.js
=> Fix/spinner infoLobby order
